### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "db19a4913a4b4c70821ee4ef46c41783",
  "accountNumber": "1000000010",
  "amount": 1000
}

### query transaction
GET http://localhost:8080/transaction/633a08f713904fa6b682f7e9f5945f9c
