### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10000000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "769547b18fd8486fb58588212ba78ba2",
  "accountNumber": "1000000001",
  "amount": 1000
}

### query transaction
GET http://localhost:8080/transaction/633a08f713904fa6b682f7e9f5945f9c
